version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.6

workflows:
  pack-and-publish:
    jobs:
      - orb-tools/lint:
          use-default-rules: false
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          context: org-global
          orb-name: picturepipe/sentry-cli
          requires:
            - orb-tools/pack
          filters:
            branches:
              only:
                - master
